
let spacesData = [
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "medium", vehicle_id: null, row: 2, level: 1, },
  {size: "large", vehicle_id: null, row: 3, level: 1, },
  {size: "large", vehicle_id: null, row: 3, level: 1, },
  {size: "large", vehicle_id: null, row: 3, level: 1, },
  {size: "large", vehicle_id: null, row: 3, level: 1, },
  {size: "large", vehicle_id: null, row: 3, level: 1, },
  {size: "large", vehicle_id: null, row: 4, level: 1, },
  {size: "large", vehicle_id: null, row: 4, level: 1, },
  {size: "large", vehicle_id: null, row: 4, level: 1, },
  {size: "large", vehicle_id: null, row: 4, level: 1, },
  {size: "large", vehicle_id: null, row: 4, level: 1, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "medium", vehicle_id: null, row: 2, level: 2, },
  {size: "large", vehicle_id: null, row: 3, level: 2, },
  {size: "large", vehicle_id: null, row: 3, level: 2, },
  {size: "large", vehicle_id: null, row: 3, level: 2, },
  {size: "large", vehicle_id: null, row: 3, level: 2, },
  {size: "large", vehicle_id: null, row: 3, level: 2, },
  {size: "large", vehicle_id: null, row: 4, level: 2, },
  {size: "large", vehicle_id: null, row: 4, level: 2, },
  {size: "large", vehicle_id: null, row: 4, level: 2, },
  {size: "large", vehicle_id: null, row: 4, level: 2, },
  {size: "large", vehicle_id: null, row: 4, level: 2, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "small", vehicle_id: null, row: 1, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "medium", vehicle_id: null, row: 2, level: 3, },
  {size: "large", vehicle_id: null, row: 3, level: 3, },
  {size: "large", vehicle_id: null, row: 3, level: 3, },
  {size: "large", vehicle_id: null, row: 3, level: 3, },
  {size: "large", vehicle_id: null, row: 3, level: 3, },
  {size: "large", vehicle_id: null, row: 3, level: 3, },
  {size: "large", vehicle_id: null, row: 4, level: 3, },
  {size: "large", vehicle_id: null, row: 4, level: 3, },
  {size: "large", vehicle_id: null, row: 4, level: 3, },
  {size: "large", vehicle_id: null, row: 4, level: 3, },
  {size: "large", vehicle_id: null, row: 4, level: 3, },
];

const createSpace = (knex, space) => {
  return knex('spaces').insert({
    size: space.size,
    vehicle_id: space.vehicle_id,
    row: space.row,
    level: space.level
  }, 'id')
}


exports.seed = function(knex, Promise) {
  return knex('spaces').del()
    .then(() => knex('vehicles').del())
    .then(() => {
      let spacePromises = [];
      spacesData.forEach(space => spacePromises.push(createSpace(knex, space)));
      return Promise.all(spacePromises);
    })
    .catch(error => console.log(error));
};
